# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-03 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180303_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponrecord',
            name='number',
            field=models.CharField(max_length=64),
        ),
    ]
